### ISSUE TITLE
compiling kpower_2d_plots.pro

### ISSUE THREAD

**Issue by bpindor** [JLBLine/chips_ozstar_tools#1]
CHIPS plotting on ozstar fails for me when kpower_2d_plots.pro is being compiled.Error below. Since it works for others maybe I need to load other idl modules?

IDL> .compile /fred/oz048/MWA/CODE/CHIPS/PS/ps_plotting/kpower_2d_plots.pro

        cb_ticknames = number_formatter(cb_tick_vals, format = format, /print_exp)
                                                              ^
% Syntax error.
  At: /fred/oz048/MWA/CODE/CHIPS/PS/ps_plotting/kpower_2d_plots.pro, Line 939
% 1 Compilation error(s) in module KPOWER_2D_PLOTS.

**Comment by JLBLine** [comment]
Just double checking, have you tried adding the lines Nichole put in the README onto you IDL_PATH? Added below for convenience:

/fred/oz048/MWA/CODE/CHIPS/PS_libs/coyote
/fred/oz048/MWA/CODE/CHIPS/PS_libs/fhdps_utils
/fred/oz048/MWA/CODE/CHIPS/PS_libs/Healpix_3.11
/fred/oz048/MWA/CODE/CHIPS/PS_libs/pro/astro
/fred/oz048/MWA/CODE/CHIPS/PS

**Comment by bpindor** [comment]
I had all of those in my IDL path, but it still didnt work. I copied Shintaro's path which is as below and now it works. Not sure if maybe it was the order of the path and I was calling some out of date versions
export IDL_PATH='<IDL_DEFAULT>:'+/fred/oz048/MWA/CODE/CHIPS/PS:+/fred/oz048/MWA/CODE/CHIPS/PS_libs/coyote:+/fred/oz048/MWA/CODE/CHIPS/PS_libs/Healpix_3.11/src/idl/:+/fred/oz048/MWA/CODE/CHIPS/PS_libs/pro:+/fred/oz048/MWA/CODE/CHIPS/PS/fhdps_utils:+/fred/oz048/MWA/CODE/CHIPS/PS_libs/fhdps_utils
