### ISSUE TITLE
Differencing CHIPS data sets

### ISSUE THREAD

**Issue by bpindor** [JLBLine/chips_ozstar_tools#2]
Is there a way of producing difference plots for different CHIPS runs under the new plotting setup?

**Comment by nicholebarry** [comment]
Not at the moment. I'll work on that feature

**Comment by nicholebarry** [comment]
@bpindor done. Check readme for description of use-case.

**Comment by bpindor** [comment]
I had an error due to the plotfile parameter having multiple values. I changed my local version by adding
 outputstring = outputstring[0] + '_' + outputstring[1] at line 484 which seems to work
