### ISSUE TITLE
Output of differencing CHIPS data sets 

### ISSUE THREAD

**Issue by syoshiura** [JLBLine/chips_ozstar_tools#3]
I ran plotting script for two data set as below,

IDL> plot_chipsout_general , ['sim_m3000_p1000_90MHz_UL', 'sim_m3000_p1000_75MHz_UL'], initials='SY',  RTS=1, twoD=1, n_freq=320, band='ultra-low', lssa_num=1, beam_point_weight = [0.,0.,0.,0.,1.,0.,0.,0.,0.], output_dir='/fred/oz048/syoshiur/CHIPS/'

Then, I got an error, 
% Expression must be a scalar or 1 element array in this context: <BYTE      Array[2, 2]>.
% Execution halted at: KPOWER_2D_PLOTS   601 /fred/oz048/MWA/CODE/CHIPS/PS/ps_plotting/kpower_2d_plots.pro
%                      PLOT_CHIPSOUT_GENERAL  513 /fred/oz048/MWA/CODE/chips_ozstar_tools/plot_chipsout_general_tmp.pro
%                      $MAIN$          

I believe this is due to output name (outputstring) is not scalar. 
output = output_dir + 'plots_'+outputstring+'_ratiodiff.png'

**Comment by nicholebarry** [comment]
Thanks @syoshiura, good catch. There was a weird difference depending on whether or not the output_dir was specified. I have fixed it, so it should work now.

**Comment by syoshiura** [comment]
Thank you, it works!! Could you also add below at line 700? Same error has happened for 1D plot. 

;Set up titles based on inputs
   if N_elements(outputstring) EQ 1 then begin
     note = outputstring
   endif else begin
     note = outputstring[0] + ‘, ’ + outputstring[1]
     outputstring = outputstring[0] + ‘__’ + outputstring[1]
   endelse
