### ISSUE TITLE
1d plot with two inputs

### ISSUE THREAD

**Issue by mahsarahimi** [JLBLine/chips_ozstar_tools#4]
I ran plotting_script with two input strings for 1D plot,like:
.compile /fred/oz048/MWA/CODE/chips_ozstar_tools/plot_chipsout_general.pro
plot_chipsout_general, ['eor1_2015_4flaggedtiles_newscript','eor1_2015_4good_flaggedtiles_newsrc'], initials='MR', RTS=1, oneD=1, n_freq=384, band='high', l
ssa_num=0, beam_point_weight= [0.,0.,0.,0.,1.,0.,0.,0.,0.], output_dir='/fred/oz048/mrahimi/MR_chips_plots'

I get this error:
Compiled module: CGROOTNAME.
% Expression must be a scalar or 1 element array in this context: <BYTE      Array[2]>.
% Execution halted at: CGPS_OPEN         242 /fred/oz048/MWA/CODE/CHIPS/PS_libs/coyote/cgps_open.pro
%                      PLOT_CHIPSOUT_GENERAL  701 /fred/oz048/MWA/CODE/chips_ozstar_tools/plot_chipsout_general.pro
%                      $MAIN$

**Comment by JLBLine** [comment]
Hey Mahsa, I just ran with this command and it ran fine for me. Looking in your output directory (sorry for snooping) I can see the expected output file as well, so I assume it worked for you? Can I close this issue now?

**Comment by nicholebarry** [comment]
This was Shintaro's error that has already been closed.

**Comment by mahsarahimi** [comment]
When I run with this command, I still get the same error.
Shintaro's error was for twoD(and two inputs) which was resolved. But I think the same problem exists for oneD(and two inputs).
The output that exists in my output directory was created by local repo that has been edited as Shitaro's comment [https://github.com/JLBLine/chips_ozstar_tools/issues/3#issuecomment-548213626](url).
