### ISSUE TITLE
wedge = 3. throws an error in plot_chipsout_general.pro

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/chips_ozstar_tools#6]
Hey @nicholebarry, I was trying to make a horizon cut by adding `wedge=3.` but I got the following error:
```
IDL> plot_chipsout_general, 'new_shape_EoR1_ForA_set2', wedge=3.,  initials='JL', oneD=1, RTS=1, band='high', n_freq=384, beam_point_weight=[0,0,0,0,1,0,0,0,0]
% Ambiguous keyword abbreviation: WEDGE.
% Execution halted at: $MAIN$
```
It does however run fine if I use `wedge_angle=103.7`, which I gather is the same thing?
```
IDL> plot_chipsout_general, 'new_shape_EoR1_ForA_set2', wedge_angle=103.7,  initials='JL', oneD=1, RTS=1, band='high', n_freq=384, beam_point_weight=[0,0,0,0,1,0,0,0,0]
```

**Comment by nicholebarry** [comment]
Oh god, this error. IDL has this "fun" feature that allows you to not have to type out the full variable name. But if you have variables that start the same, i.e. var and var_1, it will shudder and die.  

Ya, that's the same thing. I'll push a fix

**Comment by nicholebarry** [comment]
wedge is now called wedge_cut

**Comment by JLBLine** [comment]
Woot thanks
